### ISSUE TITLE
Basic autocomplete running from SOLR on VFB1

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/VFB_2#3]
Basic autocomplete = one that is enough of an improvement on the existing autocomplete to integrate into VFB1.  It needs to be fast and to follow the tuning of the [agreed spec](https://github.com/VirtualFlyBrain/VFB_2/blob/master/specs/functional_specs_pub.md#autosuggestsearch).  It needs to index anatomical classes and allow restriction to adult brain.  Optionally, could include names and synonyms of individuals.

**Comment by Robbie1977** [comment]
Require set classes preprocessed into relationships in OWL.

**Comment by dosumis** [comment]
Assume you mean tags for overlaps X, where X is some ns region we want to allow restriction of autocomplete to. For reasons discussed before, I would prefer to keep this in a field we don't display.  I'll use subset (annotation_subset in the JSON ols delivers).

* subset: adult_brain  
* subset: nervous_system

I'll generate these in a separate file.  We'll need to experiment with OWL import statements vs direct loading into OLS.  Generation script is pretty trivial, but needs to be running automatically as part of pipeline.

**Comment by dosumis** [comment]
This is dependent on OLS SOLR autocomplete tuning - now being updated to follow PhiS tuning.
